### ISSUE TITLE
Compatibility issue with 0.6.1 [fix inside]

### ISSUE THREAD

**Issue by apoapostolov** [tonifisler/foundry-token-health#12]
With 0.6.1 released on 31/5, setting-extender.js has critical compatibility issue that prevents users from accessing the Settings in their Foundry if even one activated mod has the old settings-extender.js. I checked the mods that haven't been fixed yet and use setting-extender.js and wanted to let you know that @Azzurite has released a fixed version, all you need to do is replace and re-publish. From the Discord release post:
settings-extender 1.1.3

Link: https://gitlab.com/foundry-azzurite/settings-extender/
Direct Download: https://gitlab.com/foundry-azzurite/settings-extender/-/raw/1.1.3/src/settings-extender.js

Fixes a compatibility issue with 0.6.1. Module authors have to update their usage of this. If you're a user and want to use your favorite modules on 0.6.1 immediately, you have to either wait for them or manually replace one of your settings-extender.js files (only one is enough, the fix will be applied to all of them) with this.

**Comment by tonifisler** [comment]
It should have been fixed in 30781b28394dc8e73a26fbd485d92d32cd879c20 that I quickly put together and published yesterday. Let me know if there is an issue

**Comment by notrealdan** [comment]
FYI, it was still broken for me, but then I noticed that this module would not update past 0.1.3 (checking for update reported it was already up-to-date).  I uninstalled and reinstalled token-health and it's now on 0.1.7 and functioning properly.

**Comment by tonifisler** [comment]
Yeah that's my fault. I made the wrong assumptions about how the module is kept up-to-date, and later fixed it. Sorry you had to reinstall!
